### ISSUE TITLE
Some vars cannot be set by user

### ISSUE THREAD

**Issue by achaussier** [infOpen/ansible-role-docker#8]
Distribution variables always set some values, user should set these settings

**Comment by jak** [comment]
Is this why overriding `docker_packages_to_remove` doesn't seem to work?

You'll have to forgive me if I'm mistaken - I'm relatively new to ansible.

**Comment by achaussier** [comment]
Hello,

Yes, it's the same reason. You can't override this variable, because I set it with an include.
I'll improve this part quickly, today or tomorrow.
